### ISSUE TITLE
Namespace not specified. 

### ISSUE THREAD

**Issue by Mioxiya** [1244752609/flutter_scan_kit#12]
FAILURE: Build failed with an exception.

* What went wrong:
A problem occurred configuring project ':flutter_hms_scan_kit'.
> Could not create an instance of type com.android.build.api.variant.impl.LibraryVariantBuilderImpl.
   > Namespace not specified. Specify a namespace in the module's build file. See https://d.android.com/r/tools/upgrade-assistant/set-namespace for information about setting the namespace.

     If you've specified the package attribute in the source AndroidManifest.xml, you can use the AGP Upgrade Assistant to migrate to the na
mespace value in the build file. Refer to https://d.android.com/r/tools/upgrade-assistant/agp-upgrade-assistant for general information about using the AGP Upgrade Assistant.

* Try:
> Run with --stacktrace option to get the stack trace.
> Run with --scan to get full insights.
> Get more help at https://help.gradle.org.

我遇到了这样的报错，不知道该如何解决。
这貌似是gradle8.x的要求，需要namespace
而我的本体已经指定了namespace，我没办法解决这个错误，希望能给予指导。

我使用最新版的flutter和AndroidAPI。
代码是完全复制于示例代码。

**Comment by apkcore** [comment]
遇到同样的问题，只能copy下来，增加namespace

**Comment by AccAutomaton** [comment]
> 遇到同样的问题，只能copy下来，增加namespace

我也遇到了，请教一下具体怎么做的？

**Comment by gif156359098** [comment]
可以参考这个，https://blog.csdn.net/weixin_43952004/article/details/143177043

**Comment by Mioxiya** [comment]
已解决，分享一下解决方案
增加一个批处理即可：
```gradle
subprojects {
    afterEvaluate { project ->
        if (project.hasProperty('android')) {
            project.android {
                if (namespace == null) {
                    namespace project.group
                }
                compileOptions {
                    sourceCompatibility JavaVersion.VERSION_1_8
                    targetCompatibility JavaVersion.VERSION_1_8
                }
                kotlinOptions {
                    jvmTarget = "1.8"
                }

            }
        }
    }

    project.evaluationDependsOn(":app")
}

```
